<?php

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

// Try to load our extension if it's not already loaded.
if (!extension_loaded('mdp')) {
  if (strtolower(substr(PHP_OS, 0, 3)) === 'win') {
    if (!dl('php_mdp.dll')) return;
  } else {
    // PHP_SHLIB_SUFFIX gives 'dylib' on MacOS X but modules are 'so'.
    if (PHP_SHLIB_SUFFIX === 'dylib') {
      if (!dl('mdp.so')) return;
    } else {
      if (!dl('mdp.'.PHP_SHLIB_SUFFIX)) return;
    }
  }
}



abstract class mdp {
	static function mc_set($mc) {
		mc_set($mc);
	}

	static function mc_get() {
		$r=mc_get();
		if (is_resource($r)) {
			$c=substr(get_resource_type($r), (strpos(get_resource_type($r), '__') ? strpos(get_resource_type($r), '__') + 2 : 3));
			if (class_exists($c)) return new $c($r);
			return new MadoopJobContext($r);
		}
		return $r;
	}
}

/* PHP Proxy Classes */
class MadoopJobContext {
	public $_cPtr=null;
	protected $_pData=array();

	function __set($var,$value) {
		if ($var === 'thisown') return swig_mdp_alter_newobject($this->_cPtr,$value);
		$this->_pData[$var] = $value;
	}

	function __get($var) {
		if ($var === 'thisown') return swig_mdp_get_newobject($this->_cPtr);
		return $this->_pData[$var];
	}

	function __isset($var) {
		if ($var === 'thisown') return true;
		return array_key_exists($var, $this->_pData);
	}

	function __construct($res=null) {
		if (is_resource($res) && get_resource_type($res) === '_p_Madoop__MadoopJobContext') {
			$this->_cPtr=$res;
			return;
		}
		$this->_cPtr=new_MadoopJobContext();
	}

	function textFile($uri) {
		$r=MadoopJobContext_textFile($this->_cPtr,$uri);
		if (is_resource($r)) {
			$c=substr(get_resource_type($r), (strpos(get_resource_type($r), '__') ? strpos(get_resource_type($r), '__') + 2 : 3));
			if (class_exists($c)) return new $c($r);
			return new TextFile($r);
		}
		return $r;
	}

	function imageFile($uri) {
		return MadoopJobContext_imageFile($this->_cPtr,$uri);
	}

	function videoFile($uri) {
		return MadoopJobContext_videoFile($this->_cPtr,$uri);
	}

	function audioFile($uri) {
		return MadoopJobContext_audioFile($this->_cPtr,$uri);
	}
}

class MdpObject {
	public $_cPtr=null;
	protected $_pData=array();

	function __set($var,$value) {
		if ($var === 'thisown') return swig_mdp_alter_newobject($this->_cPtr,$value);
		$this->_pData[$var] = $value;
	}

	function __get($var) {
		if ($var === 'thisown') return swig_mdp_get_newobject($this->_cPtr);
		return $this->_pData[$var];
	}

	function __isset($var) {
		if ($var === 'thisown') return true;
		return array_key_exists($var, $this->_pData);
	}
	function __construct($h) {
		$this->_cPtr=$h;
	}

	function write($uri) {
		MdpObject_write($this->_cPtr,$uri);
	}
}

class TextLine extends MdpObject {
	public $_cPtr=null;

	function __set($var,$value) {
		if ($var === 'thisown') return swig_mdp_alter_newobject($this->_cPtr,$value);
		MdpObject::__set($var,$value);
	}

	function __get($var) {
		if ($var === 'thisown') return swig_mdp_get_newobject($this->_cPtr);
		return MdpObject::__get($var);
	}

	function __isset($var) {
		if ($var === 'thisown') return true;
		return MdpObject::__isset($var);
	}

	function __construct($res=null) {
		if (is_resource($res) && get_resource_type($res) === '_p_Madoop__TextLine') {
			$this->_cPtr=$res;
			return;
		}
		$this->_cPtr=new_TextLine();
	}
}

class TextLineFilter {
	public $_cPtr=null;
	protected $_pData=array();

	function __set($var,$value) {
		if ($var === 'thisown') return swig_mdp_alter_newobject($this->_cPtr,$value);
		$this->_pData[$var] = $value;
	}

	function __get($var) {
		if ($var === 'thisown') return swig_mdp_get_newobject($this->_cPtr);
		return $this->_pData[$var];
	}

	function __isset($var) {
		if ($var === 'thisown') return true;
		return array_key_exists($var, $this->_pData);
	}

	function __construct($res=null) {
		if (is_resource($res) && get_resource_type($res) === '_p_Madoop__TextLineFilter') {
			$this->_cPtr=$res;
			return;
		}
		$this->_cPtr=new_TextLineFilter();
	}

	function c_empty() {
		return TextLineFilter_c_empty($this->_cPtr);
	}
}

class TextWord extends MdpObject {
	public $_cPtr=null;

	function __set($var,$value) {
		if ($var === 'thisown') return swig_mdp_alter_newobject($this->_cPtr,$value);
		MdpObject::__set($var,$value);
	}

	function __get($var) {
		if ($var === 'thisown') return swig_mdp_get_newobject($this->_cPtr);
		return MdpObject::__get($var);
	}

	function __isset($var) {
		if ($var === 'thisown') return true;
		return MdpObject::__isset($var);
	}

	function __construct($res=null) {
		if (is_resource($res) && get_resource_type($res) === '_p_Madoop__TextWord') {
			$this->_cPtr=$res;
			return;
		}
		$this->_cPtr=new_TextWord();
	}
}

class TextWordFilter {
	public $_cPtr=null;
	protected $_pData=array();

	function __set($var,$value) {
		if ($var === 'thisown') return swig_mdp_alter_newobject($this->_cPtr,$value);
		$this->_pData[$var] = $value;
	}

	function __get($var) {
		if ($var === 'thisown') return swig_mdp_get_newobject($this->_cPtr);
		return $this->_pData[$var];
	}

	function __isset($var) {
		if ($var === 'thisown') return true;
		return array_key_exists($var, $this->_pData);
	}

	function __construct($res=null) {
		if (is_resource($res) && get_resource_type($res) === '_p_Madoop__TextWordFilter') {
			$this->_cPtr=$res;
			return;
		}
		$this->_cPtr=new_TextWordFilter();
	}

	function c_empty() {
		return TextWordFilter_c_empty($this->_cPtr);
	}
}

class TextFile extends MdpObject {
	public $_cPtr=null;

	function __set($var,$value) {
		if ($var === 'thisown') return swig_mdp_alter_newobject($this->_cPtr,$value);
		MdpObject::__set($var,$value);
	}

	function __get($var) {
		if ($var === 'thisown') return swig_mdp_get_newobject($this->_cPtr);
		return MdpObject::__get($var);
	}

	function __isset($var) {
		if ($var === 'thisown') return true;
		return MdpObject::__isset($var);
	}

	function __construct($uri) {
		if (is_resource($uri) && get_resource_type($uri) === '_p_Madoop__TextFile') {
			$this->_cPtr=$uri;
			return;
		}
		$this->_cPtr=new_TextFile($uri);
	}
}


?>
