/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class mdp {
  public static void setMc(MadoopJobContext value) {
    mdpJNI.mc_set(MadoopJobContext.getCPtr(value), value);
  }

  public static MadoopJobContext getMc() {
    long cPtr = mdpJNI.mc_get();
    return (cPtr == 0) ? null : new MadoopJobContext(cPtr, false);
  }

}
