/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class TextFile extends MdpObject {
  private long swigCPtr;

  protected TextFile(long cPtr, boolean cMemoryOwn) {
    super(mdpJNI.TextFile_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TextFile obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mdpJNI.delete_TextFile(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public TextFile(SWIGTYPE_p_std__string uri) {
    this(mdpJNI.new_TextFile(SWIGTYPE_p_std__string.getCPtr(uri)), true);
  }

}
