/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class TextWord extends MdpObject {
  private long swigCPtr;

  protected TextWord(long cPtr, boolean cMemoryOwn) {
    super(mdpJNI.TextWord_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TextWord obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mdpJNI.delete_TextWord(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public TextWord() {
    this(mdpJNI.new_TextWord(), true);
  }

}
