/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

#ifndef PHP_MDFS_H
#define PHP_MDFS_H

extern zend_module_entry mdfs_module_entry;
#define phpext_mdfs_ptr &mdfs_module_entry

#ifdef PHP_WIN32
# define PHP_MDFS_API __declspec(dllexport)
#else
# define PHP_MDFS_API
#endif

#ifdef ZTS
#include "TSRM.h"
#endif

PHP_MINIT_FUNCTION(mdfs);
PHP_MSHUTDOWN_FUNCTION(mdfs);
PHP_RINIT_FUNCTION(mdfs);
PHP_RSHUTDOWN_FUNCTION(mdfs);
PHP_MINFO_FUNCTION(mdfs);

ZEND_NAMED_FUNCTION(_wrap_new_mdfsException);
ZEND_NAMED_FUNCTION(_wrap_new_mdfsFile);
ZEND_NAMED_FUNCTION(_wrap_mdfsFile_write);
ZEND_NAMED_FUNCTION(_wrap_mdfsFile_append);
ZEND_NAMED_FUNCTION(_wrap_mdfsFile_read);
ZEND_NAMED_FUNCTION(_wrap_new_mdfsDir);
ZEND_NAMED_FUNCTION(_wrap_new_mdfsFS);
#endif /* PHP_MDFS_H */
