/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class mdfs {
  public static void setMadoop(SWIGTYPE_p_namespace value) {
    mdfsJNI.Madoop_set(SWIGTYPE_p_namespace.getCPtr(value));
  }

  public static SWIGTYPE_p_namespace getMadoop() {
    return new SWIGTYPE_p_namespace(mdfsJNI.Madoop_get(), true);
  }

}
