/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

#define SWIGJAVA


#ifdef __cplusplus
/* SwigValueWrapper is described in swig.swg */
template<typename T> class SwigValueWrapper {
  struct SwigMovePointer {
    T *ptr;
    SwigMovePointer(T *p) : ptr(p) { }
    ~SwigMovePointer() { delete ptr; }
    SwigMovePointer& operator=(SwigMovePointer& rhs) { T* oldptr = ptr; ptr = 0; delete oldptr; ptr = rhs.ptr; rhs.ptr = 0; return *this; }
  } pointer;
  SwigValueWrapper& operator=(const SwigValueWrapper<T>& rhs);
  SwigValueWrapper(const SwigValueWrapper<T>& rhs);
public:
  SwigValueWrapper() : pointer(0) { }
  SwigValueWrapper& operator=(const T& t) { SwigMovePointer tmp(new T(t)); pointer = tmp; return *this; }
  operator T&() const { return *pointer.ptr; }
  T *operator&() { return pointer.ptr; }
};

template <typename T> T SwigValueInit() {
  return T();
}
#endif

/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#  ifndef GCC_HASCLASSVISIBILITY
#    define GCC_HASCLASSVISIBILITY
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif



/* Fix for jlong on some versions of gcc on Windows */
#if defined(__GNUC__) && !defined(__INTEL_COMPILER)
  typedef long long __int64;
#endif

/* Fix for jlong on 64-bit x86 Solaris */
#if defined(__x86_64)
# ifdef _LP64
#   undef _LP64
# endif
#endif

#include <jni.h>
#include <stdlib.h>
#include <string.h>


/* Support for throwing Java exceptions */
typedef enum {
  SWIG_JavaOutOfMemoryError = 1, 
  SWIG_JavaIOException, 
  SWIG_JavaRuntimeException, 
  SWIG_JavaIndexOutOfBoundsException,
  SWIG_JavaArithmeticException,
  SWIG_JavaIllegalArgumentException,
  SWIG_JavaNullPointerException,
  SWIG_JavaDirectorPureVirtual,
  SWIG_JavaUnknownError
} SWIG_JavaExceptionCodes;

typedef struct {
  SWIG_JavaExceptionCodes code;
  const char *java_exception;
} SWIG_JavaExceptions_t;


static void SWIGUNUSED SWIG_JavaThrowException(JNIEnv *jenv, SWIG_JavaExceptionCodes code, const char *msg) {
  jclass excep;
  static const SWIG_JavaExceptions_t java_exceptions[] = {
    { SWIG_JavaOutOfMemoryError, "java/lang/OutOfMemoryError" },
    { SWIG_JavaIOException, "java/io/IOException" },
    { SWIG_JavaRuntimeException, "java/lang/RuntimeException" },
    { SWIG_JavaIndexOutOfBoundsException, "java/lang/IndexOutOfBoundsException" },
    { SWIG_JavaArithmeticException, "java/lang/ArithmeticException" },
    { SWIG_JavaIllegalArgumentException, "java/lang/IllegalArgumentException" },
    { SWIG_JavaNullPointerException, "java/lang/NullPointerException" },
    { SWIG_JavaDirectorPureVirtual, "java/lang/RuntimeException" },
    { SWIG_JavaUnknownError,  "java/lang/UnknownError" },
    { (SWIG_JavaExceptionCodes)0,  "java/lang/UnknownError" }
  };
  const SWIG_JavaExceptions_t *except_ptr = java_exceptions;

  while (except_ptr->code != code && except_ptr->code)
    except_ptr++;

  jenv->ExceptionClear();
  excep = jenv->FindClass(except_ptr->java_exception);
  if (excep)
    jenv->ThrowNew(excep, msg);
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) if (!(expr)) {SWIG_JavaThrowException(jenv, SWIG_JavaIllegalArgumentException, msg); return nullreturn; } else


#include "mdfs/mdfs.hpp"
using namespace Madoop


#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT jlong JNICALL Java_mdfsJNI_new_1mdfsException(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  Madoop::mdfsException *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (Madoop::mdfsException *)new Madoop::mdfsException();
  *(Madoop::mdfsException **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_mdfsJNI_delete_1mdfsException(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  Madoop::mdfsException *arg1 = (Madoop::mdfsException *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(Madoop::mdfsException **)&jarg1; 
  delete arg1;
}


SWIGEXPORT jlong JNICALL Java_mdfsJNI_new_1mdfsFile_1_1SWIG_10(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  Madoop::mdfsFile *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (Madoop::mdfsFile *)new Madoop::mdfsFile();
  *(Madoop::mdfsFile **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_mdfsJNI_new_1mdfsFile_1_1SWIG_11(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  std::string *arg1 = 0 ;
  Madoop::mdfsFile *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(std::string **)&jarg1;
  if (!arg1) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "std::string const & reference is null");
    return 0;
  } 
  result = (Madoop::mdfsFile *)new Madoop::mdfsFile((std::string const &)*arg1);
  *(Madoop::mdfsFile **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_mdfsJNI_new_1mdfsFile_1_1SWIG_12(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  Madoop::mdfsFile *arg1 = 0 ;
  Madoop::mdfsFile *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Madoop::mdfsFile **)&jarg1;
  if (!arg1) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Madoop::mdfsFile const & reference is null");
    return 0;
  } 
  result = (Madoop::mdfsFile *)new Madoop::mdfsFile((Madoop::mdfsFile const &)*arg1);
  *(Madoop::mdfsFile **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_mdfsJNI_mdfsFile_1write_1_1SWIG_10(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jlong jarg3) {
  Madoop::mdfsFile *arg1 = (Madoop::mdfsFile *) 0 ;
  void *arg2 = (void *) 0 ;
  size_t arg3 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Madoop::mdfsFile **)&jarg1; 
  arg2 = *(void **)&jarg2; 
  arg3 = (size_t)jarg3; 
  try {
    (arg1)->write((void const *)arg2,arg3);
  }
  catch(Madoop::mdfsException &_e) {
    (void)_e;
    SWIG_JavaThrowException(jenv, SWIG_JavaRuntimeException, "C++ Madoop::mdfsException exception thrown");
    return ; 
  }
  
}


SWIGEXPORT void JNICALL Java_mdfsJNI_mdfsFile_1write_1_1SWIG_11(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  Madoop::mdfsFile *arg1 = (Madoop::mdfsFile *) 0 ;
  std::string *arg2 = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Madoop::mdfsFile **)&jarg1; 
  arg2 = *(std::string **)&jarg2;
  if (!arg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "std::string const & reference is null");
    return ;
  } 
  try {
    (arg1)->write((std::string const &)*arg2);
  }
  catch(Madoop::mdfsException &_e) {
    (void)_e;
    SWIG_JavaThrowException(jenv, SWIG_JavaRuntimeException, "C++ Madoop::mdfsException exception thrown");
    return ; 
  }
  
}


SWIGEXPORT void JNICALL Java_mdfsJNI_mdfsFile_1write_1_1SWIG_12(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  Madoop::mdfsFile *arg1 = (Madoop::mdfsFile *) 0 ;
  Madoop::mdfsFile *arg2 = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(Madoop::mdfsFile **)&jarg1; 
  arg2 = *(Madoop::mdfsFile **)&jarg2;
  if (!arg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Madoop::mdfsFile const & reference is null");
    return ;
  } 
  try {
    (arg1)->write((Madoop::mdfsFile const &)*arg2);
  }
  catch(Madoop::mdfsException &_e) {
    (void)_e;
    SWIG_JavaThrowException(jenv, SWIG_JavaRuntimeException, "C++ Madoop::mdfsException exception thrown");
    return ; 
  }
  
}


SWIGEXPORT void JNICALL Java_mdfsJNI_mdfsFile_1append_1_1SWIG_10(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jlong jarg3) {
  Madoop::mdfsFile *arg1 = (Madoop::mdfsFile *) 0 ;
  void *arg2 = (void *) 0 ;
  size_t arg3 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Madoop::mdfsFile **)&jarg1; 
  arg2 = *(void **)&jarg2; 
  arg3 = (size_t)jarg3; 
  try {
    (arg1)->append((void const *)arg2,arg3);
  }
  catch(Madoop::mdfsException &_e) {
    (void)_e;
    SWIG_JavaThrowException(jenv, SWIG_JavaRuntimeException, "C++ Madoop::mdfsException exception thrown");
    return ; 
  }
  
}


SWIGEXPORT void JNICALL Java_mdfsJNI_mdfsFile_1append_1_1SWIG_11(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  Madoop::mdfsFile *arg1 = (Madoop::mdfsFile *) 0 ;
  std::string *arg2 = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Madoop::mdfsFile **)&jarg1; 
  arg2 = *(std::string **)&jarg2;
  if (!arg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "std::string const & reference is null");
    return ;
  } 
  try {
    (arg1)->append((std::string const &)*arg2);
  }
  catch(Madoop::mdfsException &_e) {
    (void)_e;
    SWIG_JavaThrowException(jenv, SWIG_JavaRuntimeException, "C++ Madoop::mdfsException exception thrown");
    return ; 
  }
  
}


SWIGEXPORT void JNICALL Java_mdfsJNI_mdfsFile_1append_1_1SWIG_12(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  Madoop::mdfsFile *arg1 = (Madoop::mdfsFile *) 0 ;
  Madoop::mdfsFile *arg2 = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(Madoop::mdfsFile **)&jarg1; 
  arg2 = *(Madoop::mdfsFile **)&jarg2;
  if (!arg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "Madoop::mdfsFile const & reference is null");
    return ;
  } 
  try {
    (arg1)->append((Madoop::mdfsFile const &)*arg2);
  }
  catch(Madoop::mdfsException &_e) {
    (void)_e;
    SWIG_JavaThrowException(jenv, SWIG_JavaRuntimeException, "C++ Madoop::mdfsException exception thrown");
    return ; 
  }
  
}


SWIGEXPORT jlong JNICALL Java_mdfsJNI_mdfsFile_1read_1_1SWIG_10(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jlong jarg3) {
  jlong jresult = 0 ;
  Madoop::mdfsFile *arg1 = (Madoop::mdfsFile *) 0 ;
  void *arg2 = (void *) 0 ;
  size_t arg3 ;
  size_t result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Madoop::mdfsFile **)&jarg1; 
  arg2 = *(void **)&jarg2; 
  arg3 = (size_t)jarg3; 
  try {
    result = (arg1)->read((void const *)arg2,arg3);
  }
  catch(Madoop::mdfsException &_e) {
    (void)_e;
    SWIG_JavaThrowException(jenv, SWIG_JavaRuntimeException, "C++ Madoop::mdfsException exception thrown");
    return 0; 
  }
  
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_mdfsJNI_mdfsFile_1read_1_1SWIG_11(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  Madoop::mdfsFile *arg1 = (Madoop::mdfsFile *) 0 ;
  std::string *arg2 = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(Madoop::mdfsFile **)&jarg1; 
  arg2 = *(std::string **)&jarg2;
  if (!arg2) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "std::string const & reference is null");
    return ;
  } 
  try {
    (arg1)->read((std::string const &)*arg2);
  }
  catch(Madoop::mdfsException &_e) {
    (void)_e;
    SWIG_JavaThrowException(jenv, SWIG_JavaRuntimeException, "C++ Madoop::mdfsException exception thrown");
    return ; 
  }
  
}


SWIGEXPORT void JNICALL Java_mdfsJNI_delete_1mdfsFile(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  Madoop::mdfsFile *arg1 = (Madoop::mdfsFile *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(Madoop::mdfsFile **)&jarg1; 
  delete arg1;
}


SWIGEXPORT jlong JNICALL Java_mdfsJNI_new_1mdfsDir_1_1SWIG_10(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  Madoop::mdfsDir *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (Madoop::mdfsDir *)new Madoop::mdfsDir();
  *(Madoop::mdfsDir **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_mdfsJNI_new_1mdfsDir_1_1SWIG_11(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  std::string *arg1 = 0 ;
  Madoop::mdfsDir *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(std::string **)&jarg1;
  if (!arg1) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "std::string const & reference is null");
    return 0;
  } 
  result = (Madoop::mdfsDir *)new Madoop::mdfsDir((std::string const &)*arg1);
  *(Madoop::mdfsDir **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_mdfsJNI_delete_1mdfsDir(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  Madoop::mdfsDir *arg1 = (Madoop::mdfsDir *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(Madoop::mdfsDir **)&jarg1; 
  delete arg1;
}


SWIGEXPORT jlong JNICALL Java_mdfsJNI_new_1mdfsFS_1_1SWIG_10(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  Madoop::mdfsFS *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (Madoop::mdfsFS *)new Madoop::mdfsFS();
  *(Madoop::mdfsFS **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_mdfsJNI_new_1mdfsFS_1_1SWIG_11(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  jlong jresult = 0 ;
  std::string *arg1 = 0 ;
  Madoop::mdfsFS *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(std::string **)&jarg1;
  if (!arg1) {
    SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "std::string const & reference is null");
    return 0;
  } 
  result = (Madoop::mdfsFS *)new Madoop::mdfsFS((std::string const &)*arg1);
  *(Madoop::mdfsFS **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_mdfsJNI_delete_1mdfsFS(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  Madoop::mdfsFS *arg1 = (Madoop::mdfsFS *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(Madoop::mdfsFS **)&jarg1; 
  delete arg1;
}


#ifdef __cplusplus
}
#endif

