/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class mdfsJNI {
  public final static native long new_mdfsException();
  public final static native void delete_mdfsException(long jarg1);
  public final static native long new_mdfsFile__SWIG_0();
  public final static native long new_mdfsFile__SWIG_1(long jarg1);
  public final static native long new_mdfsFile__SWIG_2(long jarg1, mdfsFile jarg1_);
  public final static native void mdfsFile_write__SWIG_0(long jarg1, mdfsFile jarg1_, long jarg2, long jarg3);
  public final static native void mdfsFile_write__SWIG_1(long jarg1, mdfsFile jarg1_, long jarg2);
  public final static native void mdfsFile_write__SWIG_2(long jarg1, mdfsFile jarg1_, long jarg2, mdfsFile jarg2_);
  public final static native void mdfsFile_append__SWIG_0(long jarg1, mdfsFile jarg1_, long jarg2, long jarg3);
  public final static native void mdfsFile_append__SWIG_1(long jarg1, mdfsFile jarg1_, long jarg2);
  public final static native void mdfsFile_append__SWIG_2(long jarg1, mdfsFile jarg1_, long jarg2, mdfsFile jarg2_);
  public final static native long mdfsFile_read__SWIG_0(long jarg1, mdfsFile jarg1_, long jarg2, long jarg3);
  public final static native void mdfsFile_read__SWIG_1(long jarg1, mdfsFile jarg1_, long jarg2);
  public final static native void delete_mdfsFile(long jarg1);
  public final static native long new_mdfsDir__SWIG_0();
  public final static native long new_mdfsDir__SWIG_1(long jarg1);
  public final static native void delete_mdfsDir(long jarg1);
  public final static native long new_mdfsFS__SWIG_0();
  public final static native long new_mdfsFS__SWIG_1(long jarg1);
  public final static native void delete_mdfsFS(long jarg1);
}
