/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class mdfsDir {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected mdfsDir(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(mdfsDir obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mdfsJNI.delete_mdfsDir(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public mdfsDir() {
    this(mdfsJNI.new_mdfsDir__SWIG_0(), true);
  }

  public mdfsDir(SWIGTYPE_p_std__string path) {
    this(mdfsJNI.new_mdfsDir__SWIG_1(SWIGTYPE_p_std__string.getCPtr(path)), true);
  }

}
