/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.11
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class mdfsFile {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected mdfsFile(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(mdfsFile obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        mdfsJNI.delete_mdfsFile(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public mdfsFile() {
    this(mdfsJNI.new_mdfsFile__SWIG_0(), true);
  }

  public mdfsFile(SWIGTYPE_p_std__string path) {
    this(mdfsJNI.new_mdfsFile__SWIG_1(SWIGTYPE_p_std__string.getCPtr(path)), true);
  }

  public mdfsFile(mdfsFile mdf) {
    this(mdfsJNI.new_mdfsFile__SWIG_2(mdfsFile.getCPtr(mdf), mdf), true);
  }

  public void write(SWIGTYPE_p_void localMem, long size) {
    mdfsJNI.mdfsFile_write__SWIG_0(swigCPtr, this, SWIGTYPE_p_void.getCPtr(localMem), size);
  }

  public void write(SWIGTYPE_p_std__string localPath) {
    mdfsJNI.mdfsFile_write__SWIG_1(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(localPath));
  }

  public void write(mdfsFile mdf) {
    mdfsJNI.mdfsFile_write__SWIG_2(swigCPtr, this, mdfsFile.getCPtr(mdf), mdf);
  }

  public void append(SWIGTYPE_p_void localMem, long size) {
    mdfsJNI.mdfsFile_append__SWIG_0(swigCPtr, this, SWIGTYPE_p_void.getCPtr(localMem), size);
  }

  public void append(SWIGTYPE_p_std__string localPath) {
    mdfsJNI.mdfsFile_append__SWIG_1(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(localPath));
  }

  public void append(mdfsFile mdf) {
    mdfsJNI.mdfsFile_append__SWIG_2(swigCPtr, this, mdfsFile.getCPtr(mdf), mdf);
  }

  public long read(SWIGTYPE_p_void localMem, long size) {
    return mdfsJNI.mdfsFile_read__SWIG_0(swigCPtr, this, SWIGTYPE_p_void.getCPtr(localMem), size);
  }

  public void read(SWIGTYPE_p_std__string localPath) {
    mdfsJNI.mdfsFile_read__SWIG_1(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(localPath));
  }

}
