function (add_madoop_executable name )
	include_directories(${CMAKE_SOURCE_DIR}/lib/program_options)
	add_executable(${name} ${ARGN} )
	target_link_libraries(${name} boost_program_options)
endfunction(add_madoop_executable)
